### ISSUE TITLE
Изображение не дает склонировать репозиторий

### ISSUE THREAD

**Issue by nazar-si** [pyoadfe/hw5-tree#1]
Из-за того, что изображение имеет название файла, которое несовместимо с названиями файлов в Windows, при попытке склонировать репозиторий возникает ошибка, которая требует ручного разбора коммита с помощью
```git
git restore --staged .
git restore README.md
....
```
Откройте возможность сделать ветку с исправлением, чтобы отправить pull-request.

**Comment by matwey** [comment]
Спасибо. Поправил имя файла
